### ISSUE TITLE
Panic when stepping past end of program?

### ISSUE THREAD

**Issue by ggreif** [kateinoigakukun/wasminspect#20]
```
$ export RUST_BACKTRACE=full
$ ../../wasminspect/target/debug/wasminspect fib-wasm.mo.wasm
(wasminspect) breakpoint set _start
(wasminspect) run
Hit breakpoint
(wasminspect) thread step-inst-in
-> 0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
-> 0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
-> 0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
-> 0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
-> 0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
-> 0x0000d961: Call { function_index: 225 }
   0x0000d964: End
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
   0x0000d961: Call { function_index: 225 }
-> 0x0000d964: End
(wasminspect) 
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0:        0x10f86d6e5 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x10f86d6e5 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x10f86d6e5 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x10f86d6e5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x10f886f9d - core::fmt::write::hd42cb3dea57bae40
                               at src/libcore/fmt/mod.rs:1052
   5:        0x10f86b10b - std::io::Write::write_fmt::ha39f6009af02b1d2
                               at src/libstd/io/mod.rs:1426
   6:        0x10f86f3da - std::sys_common::backtrace::_print::h5cfb8cdd320f1e64
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x10f86f3da - std::sys_common::backtrace::print::hef683e3bc77ce269
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x10f86f3da - std::panicking::default_hook::{{closure}}::h389f076017b5df43
                               at src/libstd/panicking.rs:204
   9:        0x10f86f0da - std::panicking::default_hook::h04b06ec20c41bf02
                               at src/libstd/panicking.rs:224
  10:        0x10f86fa3d - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
                               at src/libstd/panicking.rs:472
  11:        0x10f86f5d2 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:        0x10f8860ff - core::panicking::panic_fmt::h272b9afd5b7b725a
                               at src/libcore/panicking.rs:85
  13:        0x10f8860c9 - core::panicking::panic_bounds_check::h4036dc05a8b9e338
                               at src/libcore/panicking.rs:63
  14:        0x10f40326f - <usize as core::slice::SliceIndex<[T]>>::index::h7dfde734d3705cf2
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791
  15:        0x10f3f2025 - core::slice::<impl core::ops::index::Index<I> for [T]>::index::hdf460730f29c4076
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2656
  16:        0x10f47d9bb - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::h1b5cd222ca04d4e3
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1883
  17:        0x10f3ebfe6 - wasminspect_vm::func::DefinedFunctionInstance::inst::h2ed6a75bc852267f
                               at crates/vm/src/func.rs:123
  18:        0x10f1fa647 - wasminspect_vm::executor::Executor::execute_step::h4213ca0e45963176
                               at /Users/ggreif/wasminspect/crates/vm/src/executor.rs:117
  19:        0x10f193937 - <wasminspect_cli::debugger::MainDebugger as wasminspect_cli::commands::debugger::Debugger>::step::hdbc5bb17b188b921
                               at crates/cli/src/debugger.rs:148
  20:        0x10f21b238 - <wasminspect_cli::commands::thread::ThreadCommand as wasminspect_cli::commands::command::Command<D>>::run::hbcd804ddba4110f9
                               at crates/cli/src/commands/thread.rs:103
  21:        0x10f1a67f6 - wasminspect_cli::process::Process<D>::dispatch_command::hf00918cc7725a1c6
                               at crates/cli/src/process.rs:73
  22:        0x10f1a622a - wasminspect_cli::process::Process<D>::run_loop::h718977ffd3717c89
                               at crates/cli/src/process.rs:59
  23:        0x10f18e16c - wasminspect_cli::run_loop::hf47ed2c73185c615
                               at crates/cli/src/lib.rs:77
  24:        0x10f0c5253 - wasminspect::main::hdc712d1017341038
                               at src/main.rs:19
  25:        0x10f0c6f62 - std::rt::lang_start::{{closure}}::hbecb1a582d5f1e54
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  26:        0x10f86f498 - std::rt::lang_start_internal::{{closure}}::hd38dd0e12f275c20
                               at src/libstd/rt.rs:52
  27:        0x10f86f498 - std::panicking::try::do_call::hf2b35caddf59127c
                               at src/libstd/panicking.rs:305
  28:        0x10f871c4b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  29:        0x10f86fdfe - std::panicking::try::hc278c045b5a17f13
                               at src/libstd/panicking.rs:281
  30:        0x10f86fdfe - std::panic::catch_unwind::h21f9aef85494420b
                               at src/libstd/panic.rs:394
  31:        0x10f86fdfe - std::rt::lang_start_internal::h8e563903bf99e7c1
                               at src/libstd/rt.rs:51
  32:        0x10f0c6f42 - std::rt::lang_start::h41e932c9310df9a8
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  33:        0x10f0c5882 - <wasminspect::Opts as structopt::StructOptInternal>::augment_clap::h2159b215644d13d2
```

Here is the wasm file: 
[fib-wasm.mo.wasm.zip](https://github.com/kateinoigakukun/wasminspect/files/4832012/fib-wasm.mo.wasm.zip)

**Comment by kateinoigakukun** [comment]
Hmm, it seems there is something wrong in wasminspect. I'll take a look in a few days.

**Comment by ggreif** [comment]
Looks like `_start` doesn't have a frame:
```
Gabors-MBP:wasmtime ggreif$ ../../wasminspect/target/debug/wasminspect fib-wasm.mo.wasm
(wasminspect) breakpoint set start
(wasminspect) run
Hit breakpoint
(wasminspect) thread info
0x293c `rts_start at ./<moc-asset>/prim::1`
(wasminspect) thread backtrace
0: rts_start
1: link_start
```

**Comment by ggreif** [comment]
A similar crash
```
(wasminspect) thread step-inst-in
No execution context
(wasminspect) run
Hit breakpoint
(wasminspect) thread step-inst-in
-> 0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
-> 0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
-> 0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
-> 0x00002944: I32Const { value: 0 }
   0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000293c: GlobalGet { global_index: 8 }
   0x0000293e: GlobalSet { global_index: 0 }
   0x00002940: I32Const { value: 65536 }
   0x00002944: I32Const { value: 0 }
-> 0x00002946: I32Store { memarg: MemoryImmediate { flags: 2, offset: 0 } }
   0x00002949: End
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
-> 0x0000d961: Call { function_index: 225 }
   0x0000d964: End
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
   0x0000d961: Call { function_index: 225 }
-> 0x0000d964: End
(wasminspect) thread backtrace
(wasminspect) thread info
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/cli/src/commands/thread.rs:50:34
stack backtrace:
  13:        0x10b98f037 - core::panicking::panic::h8627f9662a331d41
                               at src/libcore/panicking.rs:52
  14:        0x10b6854c5 - core::option::Option<T>::unwrap::hc4c2c10166e39de8
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/macros/mod.rs:10
  15:        0x10b322e28 - <wasminspect_cli::commands::thread::ThreadCommand as wasminspect_cli::commands::command::Command<D>>::run::hbcd804ddba4110f9
                               at crates/cli/src/commands/thread.rs:50
  16:        0x10b2af6f6 - wasminspect_cli::process::Process<D>::dispatch_command::hf00918cc7725a1c6
                               at crates/cli/src/process.rs:73
  17:        0x10b2af365 - wasminspect_cli::process::Process<D>::run_loop::h718977ffd3717c89
                               at crates/cli/src/process.rs:57
  18:        0x10b296f9c - wasminspect_cli::run_loop::hf47ed2c73185c615
                               at crates/cli/src/lib.rs:77
  19:        0x10b1ce083 - wasminspect::main::hdc712d1017341038
                               at src/main.rs:19
  20:        0x10b1cfd92 - std::rt::lang_start::{{closure}}::hbecb1a582d5f1e54
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  21:        0x10b978478 - std::rt::lang_start_internal::{{closure}}::hd38dd0e12f275c20
                               at src/libstd/rt.rs:52
  22:        0x10b978478 - std::panicking::try::do_call::hf2b35caddf59127c
                               at src/libstd/panicking.rs:305
  23:        0x10b97ac2b - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  24:        0x10b978dde - std::panicking::try::hc278c045b5a17f13
                               at src/libstd/panicking.rs:281
  25:        0x10b978dde - std::panic::catch_unwind::h21f9aef85494420b
                               at src/libstd/panic.rs:394
  26:        0x10b978dde - std::rt::lang_start_internal::h8e563903bf99e7c1
                               at src/libstd/rt.rs:51
  27:        0x10b1cfd72 - std::rt::lang_start::h41e932c9310df9a8
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  28:        0x10b1ce6b2 - <wasminspect::Opts as structopt::StructOptInternal>::augment_clap::h2159b215644d13d2
```

**Comment by ggreif** [comment]
Also `step-inst-in` seem to ignore the function `225`:
```
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
-> 0x0000d961: Call { function_index: 225 }
   0x0000d964: End
(wasminspect) 
   0x0000d95e: Call { function_index: 226 }
   0x0000d961: Call { function_index: 225 }
-> 0x0000d964: End
```

**Comment by ggreif** [comment]
I have the suspicion that a `DW_LNE_end_sequence` marker is missing on the top-level program fragment.  But even then there should be no crash.

**Comment by kateinoigakukun** [comment]
I've tried to fix these issues on master branch. Could you try again?
